# Generated by Django 3.2.7 on 2021-09-02 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='序号')),
                ('price_type', models.IntegerField()),
                ('picture', models.CharField(max_length=200)),
                ('project_type', models.CharField(max_length=10, verbose_name='项目类型')),
                ('content', models.CharField(max_length=200)),
                ('texture', models.CharField(max_length=100)),
                ('width', models.IntegerField()),
                ('high', models.IntegerField()),
                ('requirment', models.CharField(max_length=200)),
                ('count', models.IntegerField()),
                ('unit', models.CharField(max_length=10)),
                ('money', models.IntegerField()),
                ('outside', models.BooleanField()),
                ('need_install', models.BooleanField()),
                ('need_deliver', models.BooleanField()),
                ('need_design', models.BooleanField()),
                ('area', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=200)),
                ('texture', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=200)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=20)),
                ('salesman', models.CharField(max_length=20)),
                ('follow_man', models.CharField(max_length=20)),
                ('install_requirement', models.CharField(max_length=500, verbose_name='安装要求')),
                ('deliver_requirement', models.CharField(max_length=500, verbose_name='提货要求')),
                ('deliver_date', models.DateField(verbose_name='交货日期')),
                ('deliver_address', models.CharField(max_length=500, verbose_name='送货地址')),
                ('total_fee', models.IntegerField(verbose_name='合计金额')),
                ('tax_fee', models.IntegerField(default=0, verbose_name='税费')),
                ('discount_fee', models.IntegerField(default=0, verbose_name='优惠金额')),
                ('order_fee', models.IntegerField(verbose_name='订单金额')),
                ('pre_pay_fee', models.IntegerField(verbose_name='预付款')),
                ('pay_way', models.IntegerField(verbose_name='支付方式')),
                ('input_account', models.IntegerField(verbose_name='收款账户')),
                ('completed_time', models.DateField(verbose_name='结账日期')),
                ('design_type', models.IntegerField(verbose_name='设计类型')),
                ('design_person', models.CharField(max_length=20)),
                ('order_type', models.IntegerField(verbose_name='单据类型')),
                ('comment', models.CharField(max_length=500, verbose_name='备注')),
                ('items', models.ManyToManyField(to='management.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=200)),
                ('contract_people', models.CharField(max_length=100)),
                ('contract_tel', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('pay_way', models.IntegerField(default=0)),
                ('discount_package', models.IntegerField(default=0)),
                ('recent_contract_time', models.DateField(verbose_name='最近联系')),
                ('recent_deal_time', models.DateField(verbose_name='最近交易')),
                ('comment', models.CharField(max_length=200, verbose_name='备注')),
                ('responsable_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.employee')),
            ],
        ),
    ]
